name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Debug - list all files to check folder structure
      - name: List all repo files
        run: ls -R

      # Step 4: Build Maven project (update working-directory once we confirm path)
      - name: Build Selenium project
        run: mvn -B clean install
        working-directory: ./02-Automation_Testing/01-Java_Browser_Automation
